version: 2.1

jobs:
  test: #TODO: run tests for all forms to deploy
    working_directory: ~/project
    docker:
      - image: circleci/python:3.8.10-node
    steps:
      - checkout
  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.8.0a3-node
    parameters:
      FORM:
        description: "Determines which form to deploy"
        type: string
    steps:
      - checkout
      - run:
          name: "Print App Environment Variables"
          command: bash ./.circleci/scripts/print_vars.sh
      - run:
          name: "Install Linux Dependencies"
          command: |
            sudo apt-get update
            sudo apt-get install jq
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: "Install top-level yarn dependencies"
          command: |
            yarn install --production=false
      - run:
          name: "Deploy << parameters.FORM >> form"
          command: bash ./.circleci/scripts/deploy_one_form.sh << parameters.FORM >>

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - deploy:
          FORM: officer-complaint-form
      - deploy:
          FORM: officer-thank-form
      - deploy:
          FORM: day-labor
