# AWS
DEPLOYMENT_BUCKET=$DEPLOYMENT_BUCKET_OPO_PROD
DEPLOYMENT_PATH_EN=police-thank
DEPLOYMENT_PATH_ES=policia-agradezca

# App
NODE_ENV=production
FORM_API_URL=$FORM_API_URL_PROD

# Structure
FORM_DIR=officer-thank-form
CHAPTERS_DIR=OPO
