# AWS
DEPLOYMENT_BUCKET=$CI_PROD_BUCKET_OPO
DEPLOYMENT_PATH_EN=police-complain
DEPLOYMENT_PATH_ES=policia-queja

# App
NODE_ENV=production
FORM_API_URL=$CI_PROD_API_OPO

# Structure
FORM_DIR=officer-complaint-form
CHAPTERS_DIR=OPO

RUN_BUNDLE_ANALYZER=true
