# AWS
DEPLOYMENT_BUCKET=$DEPLOYMENT_BUCKET_OPO_PROD
DEPLOYMENT_PATH_EN=police-complain
DEPLOYMENT_PATH_ES=policia-queja

# App
NODE_ENV=production
FORM_API_URL=$FORM_API_URL_PROD

# Structure
FORM_DIR=officer-complaint-form
CHAPTERS_DIR=OPO
