language: node_js
node_js:
  - "10"
dist: trusty

# We only deploy for staging and production.
if: (branch IN (master, production) AND type = push) OR (type = pull_request)

# We require sudo
sudo: required

# We only care for curl and jq (aws output parsing)
addons:
  apt:
    packages:
      - jq
      - curl

# We are going to install AWS Cli, Heroku Cli and source our helper scripts
before_install:
    - source ./.travis/aws-helper.sh
    - sudo pip install awscli

# Jobs
jobs:
  include:
  - stage: Build Loop
    script:
    # - forms_download_repos "dependencies"
    # - forms_build_dependencies
    - forms_build
    - forms_translate
  - stage: Post-release functions
    script:
    - forms_postrelease
